services:
  traefik:
    image: traefik:v3.3.4
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    environment:
      - CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - traefik.yml:/etc/traefik/traefik.yml:ro
      - dynamic.yml:/etc/traefik/dynamic.yml:ro
      - letsencrypt-data:/etc/traefik/certs:rw
      - traefik-logs:/var/log/traefik:rw
    ports:
      - "80:80"
      - "443:443"
    networks:
      reverse-proxy:
        ipv4_address: 172.31.255.254
      socket-proxy:
        ipv4_address: 172.30.255.253
      crowdsec-internal:
        ipv4_address: 172.29.255.253
    depends_on:
      docker-socket:
        condition: service_started
    command:
      - "--certificatesresolvers.cloudflare.acme.email=${EMAIL}"
  docker-socket:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: docker-socket
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    environment:
      - ALLOW_START=0
      - ALLOW_STOP=0
      - ALLOW_RESTARTS=0
      - AUTH=0
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISABLE_IPV6=0
      - DISTRIBUTION=0
      - EVENTS=1
      - EXEC=0
      - IMAGES=0
      - INFO=1
      - NETWORKS=0
      - NODES=0
      - PING=0
      - PLUGINS=0
      - POST=0
      - PROXY_READ_TIMEOUT=240
      - SECRETS=0
      - SERVICES=0
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=0
      - VERSION=1
      - VOLUMES=0
    read_only: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /run
    networks:
      socket-proxy:
        ipv4_address: 172.30.255.254
volumes:
  letsencrypt-data:
  traefik-logs:
networks:
  reverse-proxy:
    name: reverse-proxy
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
    attachable: true
  socket-proxy:
    name: socket-proxy
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
    internal: true
